#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d 1 3 5
bspc monitor DVI-D-0 -d 2 4 6

bspc config border_width 1
bspc config window_gap 12

bspc config split_ratio 0
bspc config borderless_monocle true
bspc config gapless_monocle true

xrandr --output DVI-D-0 --mode 1360x768 --pos 1920x312 --rotate normal --output HDMI-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal --rate 144.0
feh --no-fehbg --bg-scale --no-xinerama '/home/kyomi/Pictures/wallpaper.png'

bspc rule -a Code desktop='^1'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a Spotify desktop='^4'

picom -b
eww daemon
eww open bar

code &
discord &
spotify &
google-chrome-stable &

xinput --set-prop 'pointer:Logitech G Pro ' 'libinput Accel Speed' -0.75
xinput --set-prop 'pointer:Logitech G Pro ' 'libinput Accel Profile Enabled' 0, 1
