#!/bin/bash

###############
#  Monitors   #
###############

bspc monitor HDMI-0 -d 1 2 3
bspc monitor DVI-D-0 -d 4 5 6

########################
#  bspc configuration  #
########################

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

################
#  bspc rules  #
################

bspc rule -a discord desktop='^2'
bspc rule -a Google-chrome desktop='^3'
bspc rule -a Spotify desktop='^4'

############
#  Colors  #
############

. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

###################
#  Customization  #
###################

feh --no-fehbg --bg-scale --no-xinerama "$HOME/.config/bspwm/wallpaper.png"

##############
#  Programs  #
##############

pgrep -x sxhkd > /dev/null || sxhkd &

pgrep -x Discord > /dev/null || discord &
pgrep -x spotify > /dev/null || spotify &
pgrep -x chrome > /dev/null || google-chrome-stable &

