#!/bin/bash

#
# Wallpaper
#
feh --no-fehbg --bg-scale --no-xinerama '/home/kyomi/Pictures/wallpaper.png'

#
# Monitors
#
bspc monitor HDMI-0 -d 1 3 5
bspc monitor DVI-D-0 -d 2 4 6

#
# Configuration
#
bspc config border_width 1
bspc config window_gap 12

bspc config split_ratio 0
bspc config borderless_monocle true
bspc config gapless_monocle true

#
# Window rules
#
bspc rule -a Code desktop='^1'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a Spotify desktop='^4'

#
# X Compositor
#
picom -b

#
# Bar and widgets
#
eww daemon
eww open bar

#
# Programs
#
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x code > /dev/null || code &
pgrep -x Discord > /dev/null || discord &
pgrep -x spotify > /dev/null || spotify &
pgrep -x chrome > /dev/null || google-chrome-stable &
